Traceback (most recent call last):
  File "/Users/oyvind/code/skole/master/rl-test/mountain_car.py", line 100, in <module>
    envs = gym.vector.SyncVectorEnv(
  File "/Users/oyvind/code/skole/master/rl-test/.venv/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 53, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "/Users/oyvind/code/skole/master/rl-test/.venv/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 53, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "/Users/oyvind/code/skole/master/rl-test/mountain_car.py", line 61, in thunk
    env = gym.wrappers.RecordVideo(env, f"videos/{run_name}")
  File "/Users/oyvind/code/skole/master/rl-test/.venv/lib/python3.10/site-packages/gymnasium/wrappers/record_video.py", line 74, in __init__
    raise ValueError(
ValueError: Render mode is human, which is incompatible with RecordVideo. Initialize your environment with a render_mode that returns an image, such as rgb_array.